version: '3'

services:

  nginx:
    container_name: nginx
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html/:ro
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  api:
    container_name: api
    build: ./backend
    environment:
        - HOST=redis
        - DEBUG
        - SECRET_KEY
    command: uvicorn app:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - redis

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8098:8098
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
