{
 "title": "Polly",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Polly Requests",
   "type": "graph",
   "description": "Number of inbound requests to the polly API",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlette_requests_total{path!=\"/metrics\"}"
    }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"redis\"}"
    }
   ]
  },
  {
   "title": "Redis CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"redis\"}[1m])"
    }
   ]
  },
  {
   "title": "Nginx Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Nginx CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"frontend\"}[1m])"
    }
   ]
  }
 ]
}